services:
  - type: web
    name: fifa-flask-backend
    env: python
    rootDir: backend
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
